name: Deploy to User Page

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          TSC_COMPILE_ON_ERROR: 'true'
        run: npm run build

      - name: Copy .nojekyll
        run: |
          cp -f public/.nojekyll build/.nojekyll || true

      - name: Deploy to MatthewDTorre.github.io (main)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: MatthewDTorre/MatthewDTorre.github.io
          branch: main
          folder: build
          clean: true
          single-commit: true
          token: ${{ secrets.PAGES_TOKEN }}
